version: "3.7"

services:

  # Backend API
  smart-brain-api:
    container_name: backend
    # image: node:10.16.3
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
      CLARIFAI_API_KEY: 6a077356733146f9af40003ca1cab6d9
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/smart-brain-api
    
  # Postgres
  postgres:
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "54320:5432"

  # Redis
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"